### PR TITLE
migrate off of deprecated pkg_resources namespace packages

### PR DESCRIPTION
**Pull request by eli-schwartz**
Running the testsuite, or even generally importing it from the source tree, shows several warnings linking to

https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

By deleting the `__init__.py` file entirely, we can use PEP 420 implicit namespace packages instead.

### CODE REVIEW

**Comment by akornatskyy** [comment]
the namespace package is used by other wheezy.* packages; what is the impact of this change?

**Comment by eli-schwartz** [comment]
I haven't checked what the effect is if multiple packages share the same namespace, and some use PEP 420 while some use the old style pkg_resources variety. Probably the safest thing to do is to move them all to PEP 420 at the same time.

**Comment by akornatskyy** [comment]
we need to understand the effect first or a workaround if any.

**Comment by eli-schwartz** [comment]
Unfortunately, while this works fine for pure python builds, it breaks for cythonized builds due to a bug in cython's implementation of setuptools Extensions: https://github.com/cython/cython/issues/5237

A shame, but nothing I can do about it now.

**Comment by akornatskyy** [comment]
there are 3 options (for [packaging](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/) namespace packages): (1) native namespace packages, (2) pkgutil-style namespace packages, (3) pkg_resources-style namespace packages.

unfortunately options 1-2 are not compatible with cython.

thus pkg_resources remains until related issue is fixed in cython, e.g. it supports native namespace packages.

**Pull request closed without merging**
